### PR TITLE
Import/export xls files

### PR DESCRIPTION
**Pull request by ivansg44**
Because some people still use xls files

### CODE REVIEW

**Comment by ivansg44** [comment]
@ddooley @cmrn-rhi Could one of you check out this branch and see if you can save xls files, and open them without issue in Excel? Also if you can edit an xls file in Excel, save it, and then open it in the validator? It works fine for me, but I'm on Ubuntu, so I'm using a third-party spreadsheet application.

**Comment by cmrn-rhi** [comment]
Will do.

**Comment by cmrn-rhi** [comment]
Worked great. Did the following checks:

1) Pasted new data directly into validator, validated, saved as .xls, opened in excel; experienced no data loss or unexpected formatting.
2) Pasted new data directly into validator, skipped validation step, saved as .xls, opened in excel; experienced no data loss or unexpected formatting.
3) Imported excel generated .xls file, imported it into the validator; experienced no data loss or unexpected formatting.

**Comment by ivansg44** [comment]
Excellent. Thanks @cmrn-rhi

**Pull request merged**
